import type { SpecialtyConfig } from './types'

// Evidence-only config — ACCS EM CT1 2026 selection is MSRA + interview.
// No published numerical self-assessment scoring; portfolio reviewed at interview.
export const ACCS_EM_2026: SpecialtyConfig = {
  key: 'accs_em_2026',
  name: 'ACCS (Emergency Medicine)',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/acute-care-common-stem-accs-emergency-medicine-ct1-2026',
  sourceLabel: 'NHS England — ACCS Emergency Medicine CT1 2026 Person Specification',
  isOfficial: false,
  isEvidenceOnly: true,
  domains: [
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'PhD/MD, Masters, PG Diploma/Certificate (intercalated degrees excluded from this section).',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Peer-reviewed publications, book chapters, case reports, editorials, abstracts.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings.',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Complete QI/audit cycles with documented change and re-audit; partial cycles with defined role.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Formal teaching programmes, regular teaching sessions, teaching qualifications.',
    },
    {
      key: 'commitment_em',
      label: 'Commitment to Emergency Medicine',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'MRCEM Primary, EM taster/elective, ALS/ATLS/APLS courses, EM conferences attended, RCEM membership.',
    },
  ],
}
