import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Cardiology ST4 2026 — higher specialty training, entry post-IMT or equivalent.
// Selection: portfolio + interview (no public per-band numeric matrix), so
// configured as evidence-based.
export const CARDIOLOGY_ST4_2026: SpecialtyConfig = {
  key: 'cardiology_st4_2026',
  name: 'Cardiology ST4',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/cardiology-st4-2026',
  sourceLabel: 'NHS England — Cardiology ST4 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'higher',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'mrcp_diploma',
      label: 'MRCP(UK) — Part 1 at application, full diploma by offer',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'MRCP(UK) Part 1 at time of application AND full MRCP(UK) diploma by offer date. Alternative routes: eligibility for the GIM specialist register, or completion of Irish BST in medicine plus full MRCPI by offer date.',
    },
    {
      key: 'im_stage1_capabilities',
      label: 'Internal Medicine Stage 1 capabilities',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Evidence of achievement of IM Stage 1 capabilities via UK Internal Medicine Stage 1 Training, ACCS (Internal Medicine), Broad Based Training (medicine), standalone IMY3 programme, or JRCPTB Level 3 internationally accredited programme — all evidenced by satisfactory ARCP. Or eligibility for the GIM specialist register at time of application.',
    },
    {
      key: 'cardiology_acute_medicine_experience',
      label: 'Acute medical experience (≥36 months, 18 with acute inpatients)',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Minimum 36 months medical specialty experience including 18 months managing acute medical inpatients on unselected take, OR completion of an approved IM Stage 1 / equivalent training programme. Evidence via ARCP outcomes, structured supervised learning events, MCR.',
    },
    {
      key: 'cardiology_lat_cap',
      label: 'LAT experience in Cardiology ≤24 months',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'No more than 24 months experience in LAT (Locum Appointment for Training) posts in Cardiology by post start date.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Higher degrees (MSc, MD, PhD) — intercalated BSc explicitly excluded by the 2026 person spec. Full MRCP(UK) at time of application (rather than just Part 1) is also listed as desirable.',
    },
    {
      key: 'cardiology_clinical_experience',
      label: 'Cardiology Clinical Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Evidence at core level of managing patients with cardiovascular disease and managing cardiovascular emergencies. CCU/cardiology rotations during IMT, cardiology trust-grade experience.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. Cardiovascular research particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. BCS, ESC, AHA, ACC).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles using recognised QI methodology, with documented change and re-audit. Cardiology-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience & Training',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Evidence of teaching experience and/or training in teaching: organised teaching programmes, regular teaching of medical students / IMT trainees, PG Cert in Medical Education or equivalent.',
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Management involvement commensurate with experience, NHS understanding, evidence of effective multi-disciplinary leadership.',
    },
    {
      key: 'commitment_cardiology',
      label: 'Commitment to Cardiology',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'BCS membership (including SpR/junior membership), cardiology-specific courses (e.g. echocardiography, ECG, ALS), attendance at cardiology meetings, evidence of self-reflective practice and career planning.',
    },
  ],
}
