import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Child and Adolescent Psychiatry ST1 2026 — run-through psychiatry programme.
// F2-direct entry; alternative to Core Psychiatry CT1 for candidates committed
// to working with children and young people. Selection: MSRA + interview;
// no public per-band numeric matrix, so configured as evidence-based.
export const CHILD_ADOLESCENT_PSYCH_ST1_2026: SpecialtyConfig = {
  key: 'child_adolescent_psych_st1_2026',
  name: 'Child and Adolescent Psychiatry ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/child-and-adolescent-psychiatry-st1-2026',
  sourceLabel: 'NHS England — Child and Adolescent Psychiatry ST1 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'entry',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'psych_driving_licence',
      label: 'Valid driving licence or alternative transport',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Current and in-date driving licence, or an undertaking to provide alternative means of transport, for emergency / domiciliary care responsibilities.',
    },
    {
      key: 'capp_core_knowledge',
      label: 'Core knowledge in psychotherapy, psychology & neuroscience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Appropriate knowledge of core medical care, psychotherapy, psychology and neuroscience. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'capp_research_appraisal',
      label: 'Critical appraisal of psychiatric research',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Capacity to critically appraise research in psychiatry. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'capp_communication_children',
      label: 'Communication with children, young people & families',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Ability to communicate with and advocate for children, young people and their families, including appropriate use of non-verbal communication. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'capp_commitment',
      label: 'Commitment to working with children & young people',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Demonstrable interest in psychiatry combined with a clear interest in working with children and young people. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'BSc, BA, BMedSci or equivalent (excluding intercalated BSc / honorary MA per the person spec). Higher degrees (MSc, MD, PhD).',
    },
    {
      key: 'community_exposure',
      label: 'Community-based specialty exposure',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Clinical exposure to community-based specialty (e.g. CAMHS, paediatrics community, community psychiatry). Listed as desirable in the 2026 person spec.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. CAMHS / psychiatry publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. ACAMH, Royal College of Psychiatrists CAP Faculty).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. CAMHS-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching of medical students or trainees, PG Cert in Medical Education or equivalent.',
    },
    {
      key: 'commitment_capp',
      label: 'Commitment to Child & Adolescent Psychiatry',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'CAMHS taster/elective, Royal College of Psychiatrists membership (including SAMI / student associate), child mental health courses, volunteering with children and young people, attendance at CAP / ACAMH meetings.',
    },
  ],
}
