import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Community Sexual and Reproductive Health (CSRH) ST1 2026 — small run-through
// programme. F2-direct entry. Selection: portfolio + interview; no public
// per-band numeric matrix, so configured as evidence-based.
export const CSRH_ST1_2026: SpecialtyConfig = {
  key: 'csrh_st1_2026',
  name: 'Community Sexual & Reproductive Health ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/community-sexual-and-reproductive-health-st1-2026',
  sourceLabel: 'NHS England — Community Sexual and Reproductive Health ST1 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'entry',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'csrh_acutely_ill_management',
      label: 'Initial management of acutely ill patient',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Recognition of, and ability to undertake the initial management of, an acutely ill patient. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'BSc, BA or MSc qualification (intercalated degrees explicitly excluded by the 2026 person spec). MD or PhD (research-focused, 2–3 years full-time equivalent).',
    },
    {
      key: 'csrh_clinical_experience',
      label: 'CSRH / O&G / GUM Clinical Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'O&G placements during Foundation, GUM/sexual health rotations, contraception clinics, FSRH Diploma (DFSRH) or Letter of Competence in IUT/SDI/Menopause.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. SRH / O&G / public health publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. FSRH ASM, BASHH, RCOG meetings).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. SRH / contraception / sexual health-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching of medical students or trainees, peer education in sexual health, PG Cert in Medical Education.',
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Committee roles, society leadership, NHS management understanding and resource awareness.',
    },
    {
      key: 'commitment_csrh',
      label: 'Commitment to CSRH',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'FSRH membership / DFSRH, SRH or sexual health taster/elective, BASHH STIF Foundation course, volunteer work with sexual health charities, attendance at FSRH / BASHH meetings.',
    },
  ],
}
