import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Dermatology ST3 2026 — higher specialty training. Multiple entry routes:
// medical (post-IMT, MRCP), paediatric (post-paeds, MRCPCH), or surgical
// (post-CT/ST1 surgery, MRCS). Selection: portfolio + interview (no public
// per-band numeric matrix), so configured as evidence-based.
export const DERMATOLOGY_ST3_2026: SpecialtyConfig = {
  key: 'dermatology_st3_2026',
  name: 'Dermatology ST3',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/dermatology-st3-2026',
  sourceLabel: 'NHS England — Dermatology ST3 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'higher',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'derm_postgraduate_examination',
      label: 'Postgraduate examination (route-dependent)',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Medical route: MRCP(UK) Part 1 at application AND full MRCP(UK) by offer date (or eligibility for GIM specialist register). Paediatric route: full MRCPCH by offer date. Surgical route: MRCS by offer date.',
    },
    {
      key: 'derm_core_competences',
      label: 'Core competences (route-dependent)',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Medical route: completion of IM Stage 1 Year 2 capabilities (UK Core Medical Training, ACCS-IM, IMT, or equivalent). Paediatric route: 24 months experience including 6 months Neonatology and 6 months General Paediatrics. Surgical route: CT/ST1 core surgery competences.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Higher degrees (MSc, MD, PhD). Dermatology-related research particularly valued. Diploma in Dermatology or DipRCPath (Dermatopathology) where relevant.',
    },
    {
      key: 'derm_clinical_experience',
      label: 'Dermatology Clinical Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Dermatology-specific exposure during core training, dermatology trust-grade posts, dermatology taster/elective. Awareness of basics of managing patients with dermatological conditions.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. Dermatology / skin science publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. BAD, EADV, AAD, BSID).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Evidence of involvement in a QI project or formal research project. Closed-loop audit cycles with documented change and re-audit. Dermatology-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Formal teaching qualifications (PG Cert in Medical Education or equivalent), organised teaching programmes with feedback, regular teaching of medical students or trainees.',
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Committee roles, society leadership, NHS management training, healthcare leadership programmes.',
    },
    {
      key: 'commitment_dermatology',
      label: 'Commitment to Dermatology',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'BAD membership (including SpR/junior membership), dermatology-specific courses (e.g. dermoscopy, dermatology summer school), attendance at BAD or regional dermatology meetings, dermatology electives, evidence of professional development commitment.',
    },
  ],
}
