import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Emergency Medicine ST4 2026 — higher specialty training, entry post-ACCS-EM
// (CT3/ST3) or equivalent. Selection: portfolio + interview (no public per-band
// numeric matrix), so configured as evidence-based.
export const EM_ST4_2026: SpecialtyConfig = {
  key: 'em_st4_2026',
  name: 'Emergency Medicine ST4',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/emergency-medicine-st4-2026',
  sourceLabel: 'NHS England — Emergency Medicine ST4 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'higher',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'em_membership_examination',
      label: 'MRCEM or FRCEM Intermediate by offer date',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Either MRCEM (Primary, Intermediate and OSCE) or FRCEM Intermediate Certificate (Primary, Intermediate and SJP) successfully completed by initial offers release date.',
    },
    {
      key: 'accs_em_competences',
      label: 'ACCS-EM CT1–CT3 competences',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Achievement of CT1/ST1, CT2/ST2 and CT3/ST3 ACCS-EM competences via UK ACCS-EM training (with satisfactory ARCP), OR completion of an Alternative Certificate of Readiness to Enter Higher Emergency Medicine Specialist Training. Other applicants must evidence 36 months training including 12 months EM, 3 months consecutive Acute Medicine, 6 months consecutive Anaesthesia, 6 months consecutive ICM, and 3 months consecutive Paediatric EM.',
    },
    {
      key: 'em_resuscitation_competence',
      label: 'Adult & paediatric resuscitation competence',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Competence in adult and paediatric resuscitation — both medical and trauma — evidenced via supervisor confirmation or current course certificates (ALS, APLS/EPALS, ATLS/ETC).',
    },
    {
      key: 'em_lat_cap',
      label: 'LAT experience in EM ≤24 months',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'No more than 24 months experience in LAT (Locum Appointment for Training) posts in this specialty by advertised post start date.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Higher degrees (MSc, MD, PhD), Diploma in Immediate Medical Care (DipIMC), DRCOG, DCH, or other relevant postgraduate qualifications.',
    },
    {
      key: 'em_short_courses',
      label: 'EM-relevant short training courses',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Short training courses relevant to EM (e.g. airway, ultrasound, paediatric trauma, major incident, MIMMS). Listed as desirable in the 2026 person spec.',
    },
    {
      key: 'rcem_elearning',
      label: 'RCEM e-learning modules',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Evidence of completion of Royal College of Emergency Medicine e-learning modules (RCEMLearning). Listed as desirable in the 2026 person spec.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. EM / acute care publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. RCEM Annual Scientific Conference, EuSEM, ICEM).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. EM-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching of ACCS trainees / medical students, instructor status on ALS/APLS/ATLS, PG Cert in Medical Education.',
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Committee roles, society leadership, rota / ED management responsibilities, NHS management training.',
    },
    {
      key: 'commitment_em',
      label: 'Commitment to Emergency Medicine',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Achievements relevant to EM within and outside medicine, RCEM membership, pre-hospital / BASICS involvement, EM-relevant electives, evidence of realistic insight into the specialty.',
    },
  ],
}
