import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// General Surgery ST3 2026 — higher surgical training, entry post-CST.
// Selection: portfolio + interview (no public per-band numeric matrix), so
// configured as evidence-based.
export const GENERAL_SURGERY_ST3_2026: SpecialtyConfig = {
  key: 'general_surgery_st3_2026',
  name: 'General Surgery ST3',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/general-surgery-st3-2026',
  sourceLabel: 'NHS England — General Surgery ST3 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'higher',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'mrcs_examination',
      label: 'MRCS by examination',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Successful completion of Membership of the Royal College of Surgeons (MRCS) by examination required by initial offers release date.',
    },
    {
      key: 'core_surgical_competences',
      label: 'Core surgical competences',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Evidence of core surgical competences via current UK CST (completion by post start), satisfactory CST ARCP outcome, or completed Alternative Certificate of Eligibility for Higher Surgical Training.',
    },
    {
      key: 'general_surgery_competences',
      label: 'General Surgery curriculum competences',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Completed General Surgery competencies per the Core Surgical Training curriculum, evidenced via WBPAs, eLogbook and ARCP. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'ctst_total_cap',
      label: 'Total CT/ST experience <72 months',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Less than 72 months total experience at CT/ST level by post start date. Listed as a desirable cap in the 2026 person spec but functionally an entry gate.',
    },
    {
      key: 'gen_surg_clinical_experience',
      label: 'Elective + emergency General Surgery experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Minimum 12 months elective General Surgery PLUS 12 months emergency General Surgery on-call experience, evidenced via eLogbook and rota. Listed as desirable in the 2026 person spec.',
    },
    {
      key: 'surgical_logbook',
      label: 'Validated surgical logbook',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Validated eLogbook documentation of surgical experience with consultant sign-off, including projects derived from logbook entries.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PhD/MD by research, MSc/MA/MRes, intercalated honours degrees with classification. Surgical research particularly valued.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. General Surgery-related publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. ASGBI, ESCP, AUGIS, ACPGBI).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. General Surgery-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching of CST trainees / medical students, basic surgical skills instructor status, PG Cert in Medical Education.',
    },
    {
      key: 'commitment_general_surgery',
      label: 'Commitment to General Surgery',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'ASGBI / sub-specialty society membership (ACPGBI, AUGIS, ABS), basic surgical skills training, attendance at General Surgery meetings, surgical electives, logbook-derived projects, evidence of reflective learning and commitment to specialty.',
    },
  ],
}
