import type { SpecialtyConfig } from './types'

// Evidence-only config — GP ST1 2026 selection is MSRA-only.
// No portfolio scoring at application stage; this config is for portfolio-building reference only.
export const GP_ST1_2026: SpecialtyConfig = {
  key: 'gp_st1_2026',
  name: 'GP ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://gprecruitment.hee.nhs.uk/',
  sourceLabel: 'NHS England — GP Recruitment',
  isOfficial: false,
  isEvidenceOnly: true,
  domains: [
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'PhD/MD, Masters, PG Diploma/Certificate.',
    },
    {
      key: 'publications',
      label: 'Research & Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Peer-reviewed publications, book chapters, case reports, editorials, abstracts.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings.',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Complete QI/audit cycles with documented change and re-audit; partial cycles with defined role.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Formal teaching programmes, regular teaching sessions, teaching qualifications.',
    },
    {
      key: 'commitment_gp',
      label: 'Commitment to General Practice',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'GP taster/attachment, RCGP membership, GP conferences attended, primary care projects, social prescribing or community health work.',
    },
  ],
}
