import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Histopathology ST1 2026 — points-based self-assessment scored at application stage.
// 10 official domains, 71 total points, with per-band points published in NHS England
// scoring guidance. All domains scored on highest band only.
export const HISTOPATHOLOGY_ST1_2026: SpecialtyConfig = {
  key: 'histopathology_st1_2026',
  name: 'Histopathology ST1',
  cycleYear: 2026,
  totalMax: 71,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/pathology/histopathology/histopathology-st1-training-self-assessment-scoring-guidance-for-applicants',
  sourceLabel: 'NHS England — Histopathology ST1 Self-Assessment Scoring Guidance',
  isOfficial: true,
  scoringType: 'points',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'histopath_autopsy_awareness',
      label: 'Awareness of autopsy practice',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Demonstrate awareness of autopsy practice as part of histopathology training. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'undergraduate_degrees',
      label: 'Additional Undergraduate Degrees',
      maxPoints: 3,
      scoringRule: 'highest',
      bands: [
        { label: 'Degree prior to medicine — 1st class honours or equivalent', points: 3 },
        { label: 'Degree prior to medicine — 2:1 or equivalent', points: 2 },
      ],
      notes: 'Intercalated honours degrees with classification.',
    },
    {
      key: 'postgraduate_qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 4,
      scoringRule: 'highest',
      bands: [
        { label: 'PhD or DPhil', points: 4 },
        { label: 'MD (2-year original research-based) or MPhil', points: 4 },
        { label: 'Masters (MSc/MA/MRes, 8+ months)', points: 3 },
        { label: 'MD (dissertation)', points: 3 },
        { label: 'PG Diploma or Certificate (1–10 months)', points: 2 },
      ],
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 8,
      scoringRule: 'highest',
      bands: [
        { label: 'Histopathology-related oral presentation, national/international meeting', points: 8 },
        { label: '2+ histopathology-related posters, national/international meeting', points: 8 },
        { label: '1 histopathology-related poster, national/international meeting', points: 6 },
        { label: 'Histopathology-related oral presentation, regional meeting', points: 6 },
        { label: 'Non-histopathology oral presentation, national/international meeting', points: 5 },
        { label: '2+ non-histopathology posters, national/international meeting', points: 5 },
        { label: '1 non-histopathology poster, national/international meeting', points: 4 },
        { label: 'Non-histopathology oral presentation, regional meeting', points: 4 },
        { label: '1+ posters at regional meeting(s)', points: 4 },
        { label: 'Oral presentation or 1+ posters at local meeting(s)', points: 2 },
        { label: 'Significant contributor to oral/poster at national/international meeting', points: 2 },
      ],
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 5,
      scoringRule: 'highest',
      bands: [
        { label: 'First/joint-first author of 2+ PubMed-cited original research publications', points: 5 },
        { label: 'Co-author of 2+ PubMed-cited original research publications', points: 4 },
        { label: 'First/joint-first author of 1 PubMed-cited original research publication', points: 4 },
        { label: 'Co-author of 1 PubMed-cited original research publication', points: 3 },
        { label: 'First/joint-first/co-author of 2+ PubMed-cited other publications', points: 3 },
        { label: 'First/joint-first/co-author of 1 PubMed-cited other publication', points: 3 },
        { label: '1+ abstracts, non-peer-reviewed or non-PubMed articles', points: 2 },
      ],
    },
    {
      key: 'teaching_experience',
      label: 'Teaching Experience',
      maxPoints: 10,
      scoringRule: 'highest',
      bands: [
        { label: 'Designed teaching programme with local tutors, 3+ months, formal feedback', points: 10 },
        { label: 'Organised local teaching programme, multi-session, 3+ months, formal feedback', points: 8 },
        { label: 'Provided regular teaching, 3+ months, formal feedback', points: 6 },
        { label: 'Taught medical students occasionally with formal feedback', points: 4 },
      ],
    },
    {
      key: 'teaching_training',
      label: 'Training in Teaching',
      maxPoints: 5,
      scoringRule: 'highest',
      bands: [
        { label: 'Masters-level teaching qualification', points: 5 },
        { label: 'Higher teaching qualification (PG Cert/Diploma)', points: 3 },
        { label: 'Substantial teaching training (>2 days)', points: 2 },
        { label: 'Brief teaching training (≤2 days)', points: 1 },
      ],
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement',
      maxPoints: 10,
      scoringRule: 'highest',
      bands: [
        { label: 'Leading role in design + implementation of sustainable change; complete results presented', points: 10 },
        { label: 'Leading role in design + implementation of sustainable change; results not presented', points: 8 },
        { label: 'Active participant in design + implementation; complete results presented', points: 6 },
        { label: 'Active participant in design + implementation; results not presented', points: 4 },
        { label: 'Participated in some stages of QI; at least one cycle', points: 2 },
      ],
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 8,
      scoringRule: 'highest',
      bands: [
        { label: 'National healthcare leadership/managerial role, 6+ months, positive impact', points: 8 },
        { label: 'National non-medical voluntary leadership role, 6+ months, positive impact', points: 8 },
        { label: 'Regional healthcare leadership/managerial role, 6+ months, positive impact', points: 6 },
        { label: 'Local healthcare leadership/managerial role, 6+ months, positive impact', points: 4 },
        { label: 'Local/regional non-medical voluntary leadership role, 6+ months, positive impact', points: 4 },
      ],
    },
    {
      key: 'histopathology_commitment',
      label: 'Commitment to Histopathology',
      maxPoints: 10,
      scoringRule: 'highest',
      bands: [
        { label: 'Foundation year programme or extended training period in histopathology', points: 10 },
        { label: 'Experience in histopathology lasting more than 2 days', points: 10 },
        { label: 'Brief experience in histopathology, ≤2 days', points: 6 },
      ],
    },
    {
      key: 'histopathology_activities',
      label: 'Histopathology-Related Activities',
      maxPoints: 8,
      scoringRule: 'highest',
      bands: [
        { label: 'Completed research project related to histopathology', points: 8 },
        { label: 'Histopathology-related presentation/poster at national/regional meeting', points: 8 },
        { label: 'Completed audit in histopathology', points: 6 },
        { label: 'Attended histopathology-related courses with CPD evidence', points: 4 },
        { label: 'Other histopathology-related activity with evidence', points: 4 },
      ],
    },
  ],
}
