import type { SpecialtyConfig } from './types'

// Evidence-only config — Histopathology ST1 2026 has 10 official scored domains via NHS England
// self-assessment (total 71 pts), but the per-band point breakdown within each domain is not
// publicly published. This config uses the official 10 domain headings for evidence upload only.
export const HISTOPATHOLOGY_ST1_2026: SpecialtyConfig = {
  key: 'histopathology_st1_2026',
  name: 'Histopathology ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/pathology/histopathology/histopathology-st1-training-self-assessment-scoring-guidance-for-applicants',
  sourceLabel: 'NHS England — Histopathology ST1 Self-Assessment Scoring Guidance',
  isOfficial: false,
  isEvidenceOnly: true,
  domains: [
    {
      key: 'undergraduate_degrees',
      label: 'Additional Undergraduate Degrees',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Intercalated honours degrees with classification (1st, 2:1, 2:2, distinction/merit/pass).',
    },
    {
      key: 'postgraduate_qualifications',
      label: 'Postgraduate Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'PhD/MD, Masters (MSc/MA/MRes/MPhil), PG Diploma/Certificate.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Peer-reviewed publications (PubMed-indexed), book chapters, case reports, abstracts.',
    },
    {
      key: 'teaching_experience',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes, regular formal teaching sessions with feedback.',
    },
    {
      key: 'teaching_training',
      label: 'Training in Teaching',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'PG Cert/Diploma/Masters in Medical Education, accredited teaching qualifications, teaching training courses.',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Complete QI/audit cycles with implementation, re-audit and presentation; partial cycles with defined role.',
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Formal leadership roles, committee/society officer positions, leadership training, evidence of change/impact.',
    },
    {
      key: 'histopathology_commitment',
      label: 'Commitment to Histopathology',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'FRCPath Part 1, histopathology taster/elective/attachment, national histopathology conferences, histopathology-specific online courses.',
    },
    {
      key: 'histopathology_activities',
      label: 'Histopathology-Specific Activities',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Histopathology-specific publications, audit/QI projects, research, case series, posters.',
    },
  ],
}
