import type { SpecialtyConfig } from './types'

export const OG_ST1_2026: SpecialtyConfig = {
  key: 'og_st1_2026',
  name: 'Obstetrics & Gynaecology ST1',
  cycleYear: 2026,
  totalMax: 28,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/obstetrics-and-gynaecology-st1-2026',
  sourceLabel: 'NHS England — Obstetrics & Gynaecology ST1 2026 Person Specification',
  isOfficial: false,
  domains: [
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 4,
      scoringRule: 'highest',
      bands: [
        { label: 'PhD/MD by research', points: 4 },
        { label: 'Masters (MSc/MA/MRes, 8+ months)', points: 3 },
        { label: 'PG diploma/certificate', points: 1 },
      ],
      notes: '⚠️ O&G ST1 2026 uses MSRA + interview only; NO portfolio self-assessment at application stage. Interview added a new Ethical & Governance station for 2026. This config is for portfolio-building reference only.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 6,
      scoringRule: 'highest',
      bands: [
        { label: 'First/joint-first author original research (PubMed-indexed or in press)', points: 6 },
        { label: 'Co-author original research (PubMed-indexed)', points: 4 },
        { label: 'Book chapter or multiple other publications (2+)', points: 4 },
        { label: 'Single publication (editorial/review/case report/letter)', points: 2 },
        { label: 'Published abstract or non-peer-reviewed article', points: 1 },
      ],
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 5,
      scoringRule: 'highest',
      bands: [
        { label: 'Oral 1st/2nd author national/international', points: 5 },
        { label: 'Poster 1st/2nd author national/international', points: 4 },
        { label: 'Oral 1st/2nd author regional', points: 3 },
        { label: 'Oral or poster local', points: 2 },
      ],
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 4,
      scoringRule: 'highest',
      bands: [
        { label: 'All stages of 2 complete QI/audit cycles', points: 4 },
        { label: 'Some stages of 2 cycles OR all stages of 1 complete cycle', points: 3 },
        { label: 'Some stages of a single cycle', points: 1 },
      ],
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 4,
      scoringRule: 'highest',
      bands: [
        { label: 'Organised teaching programme 3+ months with formal feedback', points: 4 },
        { label: 'Regular teaching in defined programme with formal feedback', points: 3 },
        { label: 'Occasional formal teaching (min. 3 sessions) with feedback', points: 1 },
      ],
    },
    {
      key: 'commitment_og',
      label: 'Commitment to Obstetrics & Gynaecology',
      maxPoints: 5,
      scoringRule: 'cumulative_capped',
      isCheckbox: true,
      bands: [
        { label: 'MRCOG Part 1 pass', points: 2 },
        { label: 'MRCOG Part 1 attempt (no pass)', points: 1 },
        { label: 'O&G taster week or attachment (outside normal rotations)', points: 1 },
        { label: 'Basic practical skills in O&G course', points: 1 },
        { label: 'Ultrasound course', points: 1 },
        { label: 'ALSO/MOET/PROMPT obstetric emergency course', points: 1 },
        { label: 'National O&G conference attended (1st)', points: 1 },
        { label: 'National O&G conference attended (2nd)', points: 1 },
        { label: 'Member of RCOG trainee or student society', points: 1 },
      ],
      notes: 'Points capped at 5.',
    },
  ],
}
