import type { SpecialtyConfig } from './types'

// Evidence-only config — O&G ST1 2026 uses MSRA + interview only.
// Interview added a new Ethical & Governance station for 2026. No portfolio scoring at application.
export const OG_ST1_2026: SpecialtyConfig = {
  key: 'og_st1_2026',
  name: 'Obstetrics & Gynaecology ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/obstetrics-and-gynaecology-st1-2026',
  sourceLabel: 'NHS England — Obstetrics & Gynaecology ST1 2026 Person Specification',
  isOfficial: false,
  isEvidenceOnly: true,
  domains: [
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'PhD/MD, Masters, PG Diploma/Certificate.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Peer-reviewed publications, book chapters, case reports, editorials, abstracts.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings.',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Complete QI/audit cycles with documented change and re-audit; partial cycles with defined role.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Formal teaching programmes, regular teaching sessions, teaching qualifications.',
    },
    {
      key: 'commitment_og',
      label: 'Commitment to Obstetrics & Gynaecology',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'MRCOG Part 1, O&G taster/elective, BPSiOG / ultrasound / ALSO / MOET / PROMPT obstetric emergency courses, RCOG membership, O&G conferences attended.',
    },
  ],
}
