import type { SpecialtyConfig } from './types'

// Evidence-only config — no points-based scoring claimed.
// Domains reflect the typical Ophthalmology ST1 portfolio structure but exact band-level
// scoring is not publicly published in an official RCOphth/HEE document.
export const OPHTHALMOLOGY_ST1_2026: SpecialtyConfig = {
  key: 'ophthalmology_st1_2026',
  name: 'Ophthalmology ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/ophthalmology-st1-2026',
  sourceLabel: 'NHS England — Ophthalmology ST1 2026 Person Specification',
  isOfficial: false,
  isEvidenceOnly: true,
  domains: [
    {
      key: 'qualifications',
      label: 'Qualifications & Degrees',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Postgraduate degrees (PhD/MD/MSc), intercalated honours, PG diploma/certificate.',
    },
    {
      key: 'prizes',
      label: 'Prizes & Awards',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'National exam prizes, Crombie Medal, year-firsts, research grants, presentation/poster awards.',
    },
    {
      key: 'msf',
      label: 'Multi-Source Feedback',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Supervisor-signed MSF (GP min 5 respondents, hospital min 7) within 18 months of interview if in clinical posts.',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Audit cycles (initiated, designed, implemented, re-audited), published audit, supra-regional QI guideline.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international/national/regional/local meetings — first author preferred.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Peer-reviewed original research, systematic reviews, book chapters.',
    },
    {
      key: 'teaching',
      label: 'Teaching & Education',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'Formal teaching sessions with feedback, PG Cert/Diploma in Medical Education, course delivery, examiner roles.',
    },
    {
      key: 'specialty_links',
      label: 'Commitment to Ophthalmology',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      isEvidenceOnly: true,
      notes: 'FRCOphth Part 1, Refraction Certificate, ophthalmic taster/elective, simulation activity, clinic/theatre attendance, national meetings attended.',
    },
  ],
}
