import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Ophthalmology ST1 2026 — official NHS person spec exists but per-band points are
// not publicly published. Configured as evidence-based: NHS entry requirements as
// essentials, NHS application/interview criteria as desirables for evidence upload.
export const OPHTHALMOLOGY_ST1_2026: SpecialtyConfig = {
  key: 'ophthalmology_st1_2026',
  name: 'Ophthalmology ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/ophthalmology-st1-2026',
  sourceLabel: 'NHS England — Ophthalmology ST1 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'ophthalmology_experience_cap',
      label: 'Prior ophthalmology experience ≤30 months WTE',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Whole-time-equivalent experience in Ophthalmology (including Medical Ophthalmology) must not exceed 30 months by interview date. Direct-from-Foundation applicants meet this trivially; relevant mainly for IMGs, LAT/trust-grade, or returners.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PhD/MD, Masters (MSc/MA/MRes/MPhil), PG Diploma/Certificate, intercalated honours degrees with classification.',
    },
    {
      key: 'prizes_awards',
      label: 'Prizes & Awards',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Distinction/merit at undergraduate level, prizes from medical school or national bodies, scholarships.',
    },
    {
      key: 'msf',
      label: 'Multi-Source Feedback (MSF)',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Completed MSF/360-degree feedback round (Foundation TAB or equivalent) demonstrating professional behaviours.',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Complete QI/audit cycles with documented change and re-audit; partial cycles with defined role.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Peer-reviewed publications (PubMed-indexed), book chapters, case reports, editorials, abstracts.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Formal teaching programmes, regular teaching with feedback, PG Cert in Medical Education or equivalent.',
    },
    {
      key: 'commitment_ophthalmology',
      label: 'Commitment to Ophthalmology',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Ophthalmology taster/elective, FRCOphth Part 1, RCOphth membership, conferences attended, ophthalmology-specific courses (e.g. Eye Foundation), volunteer work.',
    },
  ],
}
