import type { SpecialtyConfig } from './types'

export const OPHTHALMOLOGY_ST1_2026: SpecialtyConfig = {
  key: 'ophthalmology_st1_2026',
  name: 'Ophthalmology ST1',
  cycleYear: 2026,
  totalMax: 50,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/ophthalmology-st1-2026',
  sourceLabel: 'NHS England — Ophthalmology ST1 2026 Person Specification',
  isOfficial: true,
  domains: [
    {
      key: 'qualifications',
      label: 'Qualifications',
      maxPoints: 5,
      scoringRule: 'cumulative_capped',
      bands: [
        { label: 'PhD/DPhil (completed)', points: 4 },
        { label: 'MD/MPhil (2+ years research with supervisor letter)', points: 3 },
        { label: 'MSc/BSc/PG Cert (non-intercalated)', points: 1 },
      ],
    },
    {
      key: 'prizes',
      label: 'Prizes & Awards',
      maxPoints: 5,
      scoringRule: 'cumulative_capped',
      bands: [
        { label: 'Crombie Medal (FRCOphth Part 1 1st place)', points: 3 },
        { label: 'National undergraduate exam 1st place', points: 3 },
        { label: 'National undergraduate exam top 10%', points: 2 },
        { label: 'National undergraduate exam top 20%', points: 1 },
        { label: 'Undergraduate year-firsts', points: 2 },
        { label: 'Lead research grant (led to peer-reviewed output)', points: 1 },
        { label: 'Best presentation/poster — national/international (1st)', points: 1 },
        { label: 'Best presentation/poster — national/international (2nd)', points: 1 },
      ],
    },
    {
      key: 'msf',
      label: 'Multi-Source Feedback',
      maxPoints: 2,
      scoringRule: 'cumulative_capped',
      bands: [
        { label: 'Satisfactory MSF with good comments (GP≥5 respondents or hospital≥7, within 18 months, supervisor-signed)', points: 2 },
      ],
      notes: 'GP: min 5 respondents. Hospital: min 7 respondents. Must be within 18 months of interview if in clinical posts.',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 5,
      scoringRule: 'cumulative_capped',
      bands: [
        { label: 'Published audit or supra-regional QI guideline', points: 5 },
        { label: 'Initiated, designed, wrote up, implemented change/closed loop', points: 3 },
        { label: 'Initiated and designed with some format evidence', points: 2 },
        { label: 'Initiated, designed, wrote up (full format)', points: 2 },
        { label: 'Participation only/no specific role', points: 0 },
      ],
    },
    {
      key: 'presentations',
      label: 'Presentations',
      maxPoints: 6,
      scoringRule: 'cumulative_capped',
      bands: [
        { label: 'International oral, 1st author (presenter)', points: 3 },
        { label: 'National oral, 1st author', points: 2 },
        { label: 'Regional oral, 1st author', points: 1 },
        { label: 'International poster, 1st author', points: 1.5 },
        { label: 'National poster, 1st author', points: 1 },
        { label: 'Regional poster, 1st author', points: 0.5 },
      ],
      notes: '2026 rule: 2nd author presentations and posters score 0. One meeting per piece of work. Each achievement can only be claimed once across all domains.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 6,
      scoringRule: 'cumulative_capped',
      bands: [
        { label: 'First-author/joint first (≤6 joint first authors)', points: 3 },
        { label: '2nd–4th author (≤8 total authors)', points: 1 },
      ],
      notes: 'Peer-reviewed original research and high-quality systematic reviews only. 5th+ author: 0 pts.',
    },
    {
      key: 'teaching',
      label: 'Education & Teaching',
      maxPoints: 5,
      scoringRule: 'cumulative_capped',
      bands: [
        { label: 'Author of postgraduate academic book', points: 3 },
        { label: 'PG Cert/Diploma in Medical Education (≥60 credits, ≥8 months, separate from primary degree)', points: 2 },
        { label: 'Chapter in postgraduate academic book', points: 2 },
        { label: '≥3 formal teaching sessions across ≥3 months with feedback', points: 1 },
        { label: 'Help run course / ≥2 mock OSCE sessions / e-learning tool / e-book / teaching the teachers / formal undergraduate examining role', points: 0.5 },
      ],
    },
    {
      key: 'specialty_links',
      label: 'Ophthalmology Specialty Links & Commitment',
      maxPoints: 13,
      scoringRule: 'cumulative_capped',
      isCheckbox: true,
      bands: [
        { label: 'FRCOphth Part 1 pass', points: 3 },
        { label: 'FRCOphth Part 1 attempt (no pass)', points: 1 },
        { label: 'Refraction Certificate or Optometrist exemption', points: 1 },
        { label: 'Ophthalmic elective or undergraduate project (1st)', points: 1 },
        { label: 'Ophthalmic elective or undergraduate project (2nd)', points: 1 },
        { label: 'Taster week or FY attachment', points: 1 },
        { label: 'Clinics/theatre outside post (>3 months, ≥10 sessions)', points: 1 },
        { label: 'Simulation activity ≥4 hours/day (1st)', points: 1 },
        { label: 'Simulation activity ≥4 hours/day (2nd)', points: 1 },
        { label: 'National/International ophthalmology meeting attended (1st)', points: 1 },
        { label: 'National/International ophthalmology meeting attended (2nd)', points: 1 },
        { label: 'National/International ophthalmology meeting attended (3rd)', points: 1 },
        { label: 'Regional ophthalmology meeting attended', points: 0.5 },
        { label: 'Other peer-reviewed publication not elsewhere counted (1st author)', points: 1 },
        { label: 'Non-peer-reviewed/case report, 1st author (1st)', points: 0.5 },
        { label: 'Non-peer-reviewed/case report, 1st author (2nd)', points: 0.5 },
        { label: 'Discretionary evidence not fitting above categories (1st)', points: 1 },
        { label: 'Discretionary evidence not fitting above categories (2nd)', points: 1 },
      ],
    },
    {
      key: 'portfolio_quality',
      label: 'Portfolio Layout & Quality',
      maxPoints: 3,
      scoringRule: 'highest',
      isSelfAssessed: true,
      bands: [
        { label: 'Excellent', points: 3 },
        { label: 'Good', points: 2 },
        { label: 'Adequate', points: 1 },
        { label: 'Basic/unclear', points: 0 },
      ],
      notes: 'Self-assessed overall portfolio presentation and organisation.',
    },
  ],
}
