import type { SpecialtyConfig } from './types'

export const PAEDIATRICS_ST1_2026: SpecialtyConfig = {
  key: 'paediatrics_st1_2026',
  name: 'Paediatrics ST1',
  cycleYear: 2026,
  totalMax: 30,
  source: 'https://www.rcpch.ac.uk/education-careers/apply-paediatrics/ST1',
  sourceLabel: 'RCPCH — Apply for Paediatrics ST1',
  isOfficial: false,
  domains: [
    {
      key: 'clinical_capabilities',
      label: 'Transferable Clinical Capabilities',
      maxPoints: 8,
      scoringRule: 'highest',
      isSelfAssessed: true,
      bands: [
        { label: 'Excellent — extensive relevant clinical experience with clear transferable skills and strong reflective insight', points: 8 },
        { label: 'Good — solid experience with well-articulated transferable skills', points: 6 },
        { label: 'Satisfactory — adequate experience described with some reflection', points: 4 },
        { label: 'Basic — limited experience or minimal reflection on transferability', points: 2 },
        { label: 'Minimal — little relevant experience or very brief response', points: 0 },
      ],
      notes: 'Scored by two independent RCPCH assessors on your written application answer. Score shown is per-assessor maximum.',
    },
    {
      key: 'personal_achievements',
      label: 'Personal Achievements & Reflection',
      maxPoints: 8,
      scoringRule: 'highest',
      isSelfAssessed: true,
      bands: [
        { label: 'Excellent — impressive non-clinical achievements with deep and genuine reflection', points: 8 },
        { label: 'Good — clear achievements and thoughtful reflection', points: 6 },
        { label: 'Satisfactory — some achievements described with adequate reflection', points: 4 },
        { label: 'Basic — limited achievements or superficial reflection', points: 2 },
        { label: 'Minimal — very brief or unfocused response', points: 0 },
      ],
      notes: 'Scored by two independent RCPCH assessors. Covers leadership, volunteering, and non-clinical achievements. Score shown is per-assessor maximum.',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 5,
      scoringRule: 'highest',
      bands: [
        { label: 'Led complete QI/audit cycle with documented change and re-audit (closed loop)', points: 5 },
        { label: 'Completed all stages of a QI or audit cycle including implementation', points: 4 },
        { label: 'Participated in QI/audit with a clearly defined role', points: 3 },
        { label: 'Some participation in QI or audit', points: 2 },
        { label: 'Minor involvement only', points: 1 },
      ],
    },
    {
      key: 'academic_achievements',
      label: 'Academic Achievements',
      maxPoints: 4,
      scoringRule: 'cumulative_capped',
      bands: [
        { label: 'PhD/MD by research (completed)', points: 4 },
        { label: 'First-author publication in peer-reviewed indexed journal', points: 3 },
        { label: 'Masters degree (MSc/MA/MRes, non-intercalated)', points: 2 },
        { label: 'Co-author publication in peer-reviewed indexed journal', points: 2 },
        { label: 'National/international oral or poster presentation (1st author)', points: 2 },
        { label: 'Regional presentation (1st author)', points: 1 },
        { label: 'Intercalated degree with merit or distinction', points: 1 },
        { label: 'PG certificate/diploma or intercalated degree (standard pass)', points: 1 },
      ],
      notes: 'Points capped at 4.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 5,
      scoringRule: 'highest',
      bands: [
        { label: 'Developed and delivered structured teaching programme 3+ months with formal feedback', points: 5 },
        { label: 'PG Certificate/Diploma in Medical Education OR led regular formal teaching (2+ months) with feedback', points: 3 },
        { label: 'Regular formal teaching sessions with documented feedback', points: 2 },
        { label: 'Occasional formal teaching or teaching training course attended', points: 1 },
      ],
    },
  ],
}
