import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Public Health and General Practice Dual Programme ST1 2026 — combined run-through
// programme leading to dual CCT in PH and GP. F2-direct entry. Selection: portfolio
// + interview; no public per-band numeric matrix, so configured as evidence-based.
export const PH_GP_DUAL_ST1_2026: SpecialtyConfig = {
  key: 'ph_gp_dual_st1_2026',
  name: 'Public Health & GP Dual Programme ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/public-health-and-general-practice-dual-programme-st1-2026',
  sourceLabel: 'NHS England — Public Health and General Practice Dual Programme ST1 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'entry',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'gp_performers_list',
      label: "Eligible for UK Performers' Lists",
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: "Eligibility for the UK Medical Performers' List (England) or equivalent for the four UK nations — required for the GP component of training.",
    },
    {
      key: 'driving_licence',
      label: 'Valid driving licence or alternative transport',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Current and in-date driving licence, or an undertaking to provide alternative means of transport. Listed as an essential in the 2026 person spec.',
    },
    {
      key: 'phgp_health_determinants',
      label: 'Understanding of health determinants',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Understanding of health, disease, and illness, and of structural, environmental and behavioural determinants of health. Listed as a specialty-specific technical essential in the 2026 person spec.',
    },
    {
      key: 'phgp_political_awareness',
      label: 'Political & policy awareness',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Awareness of national policy and its impact on health. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'phgp_research_methodology',
      label: 'Research methodology, statistics & epidemiology',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Basic understanding of research methodology including research ethics, statistics and epidemiology, with ability to critically appraise a scientific research paper. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'phgp_strategic_thinking',
      label: 'Critical & strategic thinking',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Capability for critical and strategic thinking to understand and solve complex problems, with numerical, critical thinking and verbal reasoning skills. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'phgp_long_timescales',
      label: 'Working with long delivery timescales',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Capability to work with long timescales for delivery within agencies with differing priorities — distinct from acute clinical work. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'phgp_resilience',
      label: 'Initiative & resilience to change',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Initiative and resilience to adapt and respond to changing circumstances. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'MSc / MA / MRes (e.g. Public Health, Health Economics, Epidemiology), MD, PhD. MFPH Part A by examination. PG qualifications in primary care.',
    },
    {
      key: 'phgp_dual_understanding',
      label: 'Understanding of PH and GP roles & interaction',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Understanding of the respective roles of Public Health and General Practice and the interaction between the two. Listed as desirable in the 2026 person spec.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. Public health, primary care or epidemiology publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. FPH conferences, SAPC, RCGP).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. Population-health or primary-care projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching of medical students or trainees, PG Cert in Medical Education or equivalent.',
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Committee roles, NHS management training, healthcare leadership programmes, understanding of NHS resources and management.',
    },
    {
      key: 'commitment_phgp',
      label: 'Commitment to PH & GP',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PH or GP taster/elective, FPH / RCGP membership (including AiT / GPST), public health volunteer work, attendance at FPH / RCGP meetings, evidence of realistic insight into both specialties and motivation for the dual programme.',
    },
  ],
}
