import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Plastic Surgery ST3 2026 — higher surgical training. Entry post-CST or equivalent
// (Alternative Certificate of Eligibility for Higher Surgical Training). MRCS by
// examination is mandatory. Selection: portfolio + interview. Per-band numeric
// scoring is not publicly published, so configured as evidence-based.
export const PLASTIC_SURGERY_ST3_2026: SpecialtyConfig = {
  key: 'plastic_surgery_st3_2026',
  name: 'Plastic Surgery ST3',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/plastic-surgery-st3-2026',
  sourceLabel: 'NHS England — Plastic Surgery ST3 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'higher',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'core_surgical_competences',
      label: 'Core surgical competences',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Evidence of core surgical competences via current UK CST (completion by post start), satisfactory CST ARCP outcome, or completed Alternative Certificate of Eligibility for Higher Surgical Training.',
    },
    {
      key: 'mrcs_examination',
      label: 'MRCS by examination',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Successful completion of Membership of the Royal College of Surgeons (MRCS) by examination required by initial offers release date.',
    },
    {
      key: 'lat_experience_cap',
      label: 'LAT experience in plastics ≤24 months',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'No more than 24 months experience in LAT (Locum Appointment for Training) posts in Plastic Surgery by advertised post start date.',
    },
    {
      key: 'plastics_clinical_experience',
      label: 'Plastic Surgery Experience (≥4 months desirable)',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'A minimum of 4 months experience in Plastic Surgery by post start date is listed as desirable. Evidence via CST plastics rotation, trust-grade plastics, plastics taster/elective.',
    },
    {
      key: 'surgical_logbook',
      label: 'Validated surgical logbook',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Validated eLogbook documentation of surgical exposure with consultant sign-off. Demonstrates technical and clinical competence development.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PhD/MD by research, MSc/MA/MRes, intercalated honours degrees with classification. Plastics or reconstruction-related research particularly valued.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. Plastic surgery-related publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. BAPRAS, EURAPS, BSSH, BAAPS).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. Plastic surgery-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching of CST trainees / medical students, PG Cert in Medical Education or equivalent.',
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Committee roles, society leadership, NHS management training, healthcare leadership programmes.',
    },
    {
      key: 'commitment_plastics',
      label: 'Commitment to Plastic Surgery',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'BAPRAS / BSSH membership, plastic surgery courses (e.g. flaps, microsurgery, hand trauma), attendance at plastics meetings, plastics-relevant electives, evidence of reflective learning in plastic surgery.',
    },
  ],
}
