import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Psychiatry of Learning Disability ST1 2026 — run-through psychiatry programme.
// F2-direct entry; alternative to Core Psychiatry CT1 for candidates committed
// to working with people with learning disabilities. Selection: MSRA + interview;
// no public per-band numeric matrix, so configured as evidence-based.
export const PSYCH_LEARNING_DISABILITY_ST1_2026: SpecialtyConfig = {
  key: 'psych_learning_disability_st1_2026',
  name: 'Psychiatry of Learning Disability ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/psychiatry-of-learning-disability-st1-2026',
  sourceLabel: 'NHS England — Psychiatry of Learning Disability ST1 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'entry',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'psych_driving_licence',
      label: 'Valid driving licence or alternative transport',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Current and in-date driving licence, or an undertaking to provide alternative means of transport — community LD psychiatry placements typically require travel between sites.',
    },
    {
      key: 'pld_core_knowledge',
      label: 'Core knowledge in psychotherapy, psychology & neuroscience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Appropriate knowledge of core medical care, psychotherapy, psychology and neuroscience. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'pld_research_appraisal',
      label: 'Critical appraisal of psychiatric research',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Capacity to critically appraise research in psychiatry. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'pld_diagnostic_leadership',
      label: 'Lead in diagnosis & prognosis',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Capacity to take the lead in diagnosis and prognosis. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'pld_long_term_care',
      label: 'Patience with long-term care plans',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Patience to continue the long-term care plan of the patient regardless of severity or prognosis — fundamental to LD psychiatry. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'pld_advocacy',
      label: 'Patient advocacy & holistic care',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Capacity to act as advocate on behalf of the patient when required, take a holistic approach, build relationships with patients and families, and work in partnership. Listed as specialty-specific essentials in the 2026 person spec.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'BSc, BA, BMedSci or equivalent (excluding intercalated BSc / honorary MA per the person spec). Higher degrees (MSc, MD, PhD).',
    },
    {
      key: 'community_exposure',
      label: 'Community-based specialty exposure',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Clinical exposure to community-based specialty (community LD teams, community psychiatry, community paediatrics). Listed as desirable in the 2026 person spec.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. LD psychiatry / neurodevelopmental publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. RCPsych Faculty of LD Psychiatry meetings, IASSIDD).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. LD-themed projects particularly valued (e.g. STOMP, LeDeR, annual health checks).',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching of medical students or trainees, PG Cert in Medical Education.',
    },
    {
      key: 'commitment_pld',
      label: 'Commitment to Psychiatry of Learning Disability',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'LD psychiatry taster/elective, RCPsych membership (including SAMI / student associate), volunteer work with people with learning disabilities (e.g. Mencap, befriending), attendance at RCPsych LD Faculty meetings, evidence of insight into LD psychiatry.',
    },
  ],
}
