import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Trauma & Orthopaedic Surgery ST3 2026 — higher surgical training, entry post-CST.
// Selection: portfolio + interview (no public per-band numeric matrix), so
// configured as evidence-based.
export const TO_ST3_2026: SpecialtyConfig = {
  key: 'to_st3_2026',
  name: 'Trauma & Orthopaedic Surgery ST3',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/trauma-and-orthopaedic-surgery-st3-2026',
  sourceLabel: 'NHS England — Trauma & Orthopaedic Surgery ST3 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  trainingLevel: 'higher',
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'mrcs_examination',
      label: 'MRCS by examination',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Successful completion of Membership of the Royal College of Surgeons (MRCS) by examination required by initial offers release date.',
    },
    {
      key: 'core_surgical_competences',
      label: 'Core surgical competences',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Evidence of core surgical competences via current UK CST (completion by post start), satisfactory CST ARCP outcome, or completed Alternative Certificate of Eligibility for Higher Surgical Training.',
    },
    {
      key: 'atls_competence',
      label: 'Advanced Trauma Life Support competence',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Demonstrable and up-to-date competences in advanced trauma life support (ATLS or equivalent) at the time of interview. Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'lat_experience_cap',
      label: 'LAT experience in T&O ≤24 months',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'No more than 24 months experience in LAT (Locum Appointment for Training) posts in this specialty by advertised post start date.',
    },
    {
      key: 'surgical_logbook',
      label: 'Validated surgical logbook',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Validated logbook documentation of surgical experience (eLogbook consolidation report with consultant sign-off). Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'related_specialty_experience',
      label: 'Experience in related specialties (≥8 months desirable)',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'At least 8 months experience across related specialties: Plastic, Neuro, Vascular, ENT, Cardiothoracic, A&E, ITU, Urology, OMFS, General Surgery. Evidenced via CST rotation logbook and ARCP.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PhD/MD by research, MSc/MA/MRes, intercalated honours degrees with classification. Orthopaedic / musculoskeletal research particularly valued.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed peer-reviewed publications, book chapters, case reports, editorials, abstracts. T&O-related publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. BOA, BTS, EFORT).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. T&O-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching of CST trainees / medical students, PG Cert in Medical Education or equivalent.',
    },
    {
      key: 'commitment_to',
      label: 'Commitment to T&O',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'BOA membership, orthopaedic casting technique courses, basic surgical skills courses, attendance at orthopaedic meetings, defined career planning, T&O electives, evidence of reflective and analytical approach to practice.',
    },
  ],
}
